---
- hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: devopsresourcegroup
        location: centralus
      register: rg 
 
