- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
     - group_vars/default/main.yml
     - group_vars/network/main.yml
  
  roles:
    - { role: virtual-network, network_items: "{{ network_variables }}" }
