- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
     - group_vars/default/main.yml
     - group_vars/vpc/main.yml
  
  roles:
    - common/ec2/vpc
    - common/ec2/network-acl
    - { role: common/ec2/route-table, route_table_items: "{{ route_table_public }}" }
