network_variables:
    myresources: "myresources"
    location: "Central India"
    imagePublisher: "Canonical"
    imageOffer: "UbuntuServer"
    OSDiskName: "osdiskforlinuxsimple"
    nicName: "myVMNic"
    addressPrefix: "192.0.2.0/24"
    subnetName: "Subnet"
    subnetPrefix: "10.0.0.0/24"
    storageAccountType: "Standard_LRS"
    publicIPAddressName: "myPublicIP"
    publicIPAddressType: "Dynamic"
    vmStorageAccountContainerName: "vhds"
    vmName: "MyUbuntuVM"
    vmSize: "Standard_D1"
    virtualNetworkName: "MyVNET"
    vnetID: "[resourceId('Microsoft.Network/virtualNetworks',variables('virtualNetworkName'))]"
    subnetRef: "[concat(variables('vnetID'),'/subnets/',variables('subnetName'))]"
