- name: Create Azure Deploy
  azure_rm_deployment:
    state: present
    resource_group_name: "{{ myresources }}"

    template:
      $schema: "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#"
      contentVersion: "1.0.0.0"
      parameters:
        newStorageAccountName:
          type: "string"
          value:
          metadata:
            description: "Unique DNS Name for the Storage Account where the Virtual Machine's disks will be placed."
        adminUsername:
          type: "string"
          value:
          metadata:
            description: "User name for the Virtual Machine."
        adminPassword:
          type: "securestring"
          value:
          metadata:
            description: "Password for the Virtual Machine."
        dnsNameForPublicIP:
          type: "string"
          value:
          metadata:
            description: "Unique DNS Name for the Public IP used to access the Virtual Machine."
        ubuntuOSVersion:
          type: "string"
          defaultValue: "14.04.2-LTS"
          allowedValues:
            - "12.04.5-LTS"
            - "14.04.2-LTS"
            - "15.04"
          metadata:
            description: >
                         The Ubuntu version for the VM. This will pick a fully patched image of this given Ubuntu version.
                         Allowed values: 12.04.5-LTS, 14.04.2-LTS, 15.04."
      
      resources:
        - type: "Microsoft.Network/virtualNetworks"
          apiVersion: "2015-05-01-preview"
          name: "{{ virtualNetworkName }}"
          location:  "{{ location }}"
          properties:
            addressSpace:
              addressPrefixes:
                -  "{{ addressPrefix }}"
            subnets:
              - name: "{{ subnetName }}"
                properties:
                  addressPrefix: "{{ subnetPrefix }}"
 
  
              
