- name: Create Azure Deploy
  azure_rm_deployment:
    state: present
    resource_group_name: "{{ resource_group }}"
   # parameters:
   # template:
   #   $schema: ""
    resources:
        - type: "Microsoft.Network/virtualNetworks"
          apiVersion: "2015-05-01-preview"
          name: "[variables('virtualNetworkName')]"
          location: "[variables('location')]"
          properties:
            addressSpace:
              addressPrefixes:
                - "[variables('addressPrefix')]"
            subnets:
              - name: "[variables('subnetName')]"
                properties:
                  addressPrefix: "[variables('subnetPrefix')]"
