- name: Create Azure Deploy
  azure_rm_deployment:
    state: present
    resource_group_name: "{{ myresources }}"
    template:
      $schema: "{{ lookup('file', 'VirtualNetworkTemplate.json') }}"
      contentVersion: "1.0.0.0"
      resources:
        - type: "Microsoft.Network/virtualNetworks"
          apiVersion: "2015-05-01-preview"
          name: "{{ virtualNetworkName }}"
          location:  "{{ location }}"
          properties:
            addressSpace:
              addressPrefixes:
                -  "{{ addressPrefix }}"
            subnets:
              - name: "{{ subnetName }}"
                properties:
                  addressPrefix: "{{ subnetPrefix }}"
 
  
             
