- name: creating virtual network 
  azure_rm_deployment:
    state: present
    resource_group_name: "{{ resource_group }}"
    template:
      $schema: "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#"
      contentVersion: "1.0.0.0"

      resources:
        - type: "Microsoft.Network/virtualNetworks"
          apiVersion: "2015-05-01-preview"
          name: "{{ item.virtualNetworkName }}"
          location: "{{ item.location }}"
          properties:
            addressSpace:
              addressPrefixes:
                - "{{ item.addressPrefix }}"
            subnets:
              - name: "{{ item.subnetName }}"
                properties:
                  addressPrefix: "{{ item.subnetPrefix }}"
  with_items: "{{ variables }}"
              
