- name: Create Azure Deploy
  azure_rm_deployment:
    state: present
    resource_group_name: "{{ myresources }}"
        location: "Central India"
    parameters:
       siteLocation:
          value: Central India
    template:
      $schema: "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#"
      contentVersion: "1.0.0.0"
      location: "{{ location }}"
      deployment-name: "mypx"
      resources:
        - type: "Microsoft.Network/virtualNetworks"
          apiVersion: "2015-05-01-preview"
          name: "{{ virtualNetworkName }}"
          location:  "{{ location }}"
          properties:
            addressSpace:
              addressPrefixes:
                -  "{{ addressPrefix }}"
            subnets:
              - name: "{{ subnetName }}"
                properties:
                  addressPrefix: "{{ subnetPrefix }}"
 
  
             
