- name: Create Azure Deploy
  azure_rm_deployment:
    state: present
    resource_group_name: "myresources"
    template:
      $schema: "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#"
      contentVersion: "1.0.0.0"
      #parameters:
       #  name:
        #  type: "string"
         # metadata:
          #  description: "Unique 
      resources:
        - type: "Microsoft.Network/virtualNetworks"
          apiVersion: "2015-05-01-preview"
          name:  "MyVNET"
          location: "Central India"
          properties:
            addressSpace:
              addressPrefixes:
                - "192.0.2.0/24"
            subnets:
              - name: "Subnet"
                properties:
                  addressPrefix: "10.0.0.0/24"

