- name: Create Azure Deploy
  azure_rm_deployment:
    state: present
    resource_group_name: "{{ myresources }}"
    location: "{{ location }}"
    template:
      $schema: "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#"
      contentVersion: "1.0.0.0"
      resources:
        - type: "Microsoft.Network/virtualNetworks"
          apiVersion: "2015-05-01-preview"
          name: "{{ virtualNetworkName }}"
          location:  "{{ location }}"
          properties:
            addressSpace:
              addressPrefixes:
                -  "{{ addressPrefix }}"
            subnets:
              - name: "{{ subnetName }}"
                properties:
                  addressPrefix: "{{ subnetPrefix }}"
        - type: "Microsoft.Network/publicIPAddresses"
          apiVersion: "2015-05-01-preview"
          name: "{{ publicIPAddressName }}"
          location: "{{ location }}"
          properties:
            publicIPAllocationMethod: "{{ publicIPAddressType }}"
            dnsSettings:
              domainNameLabel: "{{ dnsNameForPublicIP }}"
        - type: "Microsoft.Network/networkInterfaces"
          apiVersion: "2015-05-01-preview"
          name: "{{ nicName }}"
          location: "{{ location }}"
          dependsOn:
            - "[concat('Microsoft.Network/publicIPAddresses/', '{{ publicIPAddressName }}' )]"
            - "[concat('Microsoft.Network/virtualNetworks/', '{{ virtualNetworkName }}' )]"
          properties:
            ipConfigurations:
              - name: "ipconfig1"
                properties:
                  privateIPAllocationMethod: "Dynamic"
                  publicIPAddress:
                    id: "[resourceId('Microsoft.Network/publicIPAddresses','{{ publicIPAddressName }}' )]"
                  subnet:
                    id: "{{ subnetRef }}"
 
  
              
             
